name: Neurobeer CI

on:
  push:
    branches:
    - dev
  pull_request:
    branches:
    - master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
      with:
        ref: dev
      if: github.event == 'push'
    - name: Build the Docker dev image
      env:
        DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
        DOCKER_HUB_KEY: ${{ secrets.DOCKER_HUB_KEY }}
      run: |
        echo `pwd`
        echo 'Docker login'
        docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_KEY
        echo 'Building docker image...'
        docker build . --file ../container/Dockerfile --tag kaitj/neurobeer:dev
        echo 'Pushing docker image...'
        docker push kaitj/neurobeer:dev
        echo 'Finished deploying docker image!'
