name: Neurobeer CI

on:
  push:
    branches:
    - dev
  pull_request:
    branches:
    - master
    types: [closed]

jobs:
  docker_deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout correct branch
    - uses: actions/checkout@v1
      with:
          ref: ${{ github.ref }}

    # Double check branch - mainly for debugging purposes
    - name: Check branch
      run: |
        git branch
        echo 'If HEAD is detached, not an issue'

    # Build and deploy docker dev image
    - name: Build & deploy Docker dev image
      if: github.ref == 'refs/heads/dev'
      env:
        DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
        DOCKER_HUB_KEY: ${{ secrets.DOCKER_HUB_KEY }}
      run: |
        echo 'Docker login'
        echo ''
        docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_KEY
        echo ''
        echo 'Building docker image...'
        echo ''
        cd container
        docker build . --tag kaitj/neurobeer:dev
        echo ''
        echo 'Pushing docker image...'
        echo ''
        docker push kaitj/neurobeer:dev
        echo ''
        echo 'Finished deploying docker image!'

    # Build and deploy docker image
    - name: Build & deploy Docker latest image
      if: github.ref == 'refs/heads/master'
      env:
        DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
        DOCKER_HUB_KEY: ${{ secrets.DOCKER_HUB_KEY }}
      run: |
        echo 'Docker login'
        echo ''
        docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_KEY
        echo ''
        echo 'Building docker image...'
        echo ''
        cd container
        docker build . --tag kaitj/neurobeer:latest
        echo ''
        echo 'Pushing docker image...'
        echo ''
        docker push kaitj/neurobeer:dev
        echo ''
        echo 'Finished deploying docker image!'
